package com.example.demo.domain.entity.organizations;

public class OrganizationsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.id
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private Long id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.id
	 * @return  the value of organizations.id
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.id
	 * @param id  the value for organizations.id
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}
}