package com.example.demo.domain.entity.organizations;

import java.util.Date;

public class Organizations extends OrganizationsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.name
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.description
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.code
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.note
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.address
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.tel
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.deleted
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private Boolean deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.create_date
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organizations.update_date
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	private Date updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.name
	 * @return  the value of organizations.name
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.name
	 * @param name  the value for organizations.name
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.description
	 * @return  the value of organizations.description
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.description
	 * @param description  the value for organizations.description
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.code
	 * @return  the value of organizations.code
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.code
	 * @param code  the value for organizations.code
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.note
	 * @return  the value of organizations.note
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.note
	 * @param note  the value for organizations.note
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.address
	 * @return  the value of organizations.address
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.address
	 * @param address  the value for organizations.address
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.tel
	 * @return  the value of organizations.tel
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.tel
	 * @param tel  the value for organizations.tel
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.deleted
	 * @return  the value of organizations.deleted
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.deleted
	 * @param deleted  the value for organizations.deleted
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.create_date
	 * @return  the value of organizations.create_date
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.create_date
	 * @param createDate  the value for organizations.create_date
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organizations.update_date
	 * @return  the value of organizations.update_date
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organizations.update_date
	 * @param updateDate  the value for organizations.update_date
	 * @mbg.generated  Sun Apr 26 21:53:42 JST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}