package com.example.demo.domain.entity.users;

public class UsersKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbg.generated  Thu Apr 30 21:45:41 JST 2020
	 */
	private Long id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbg.generated  Thu Apr 30 21:45:41 JST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbg.generated  Thu Apr 30 21:45:41 JST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}
}