package com.example.demo.domain.mapper.organizations;

import com.example.demo.domain.entity.organizations.Organizations;
import com.example.demo.domain.entity.organizations.OrganizationsExample;
import com.example.demo.domain.entity.organizations.OrganizationsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    long countByExample(OrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    int deleteByExample(OrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    int deleteByPrimaryKey(OrganizationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    int insert(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    int insertSelective(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    List<Organizations> selectByExample(OrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    Organizations selectByPrimaryKey(OrganizationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    int updateByExampleSelective(@Param("record") Organizations record, @Param("example") OrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    int updateByExample(@Param("record") Organizations record, @Param("example") OrganizationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    int updateByPrimaryKeySelective(Organizations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organizations
     *
     * @mbg.generated Mon Apr 20 12:03:25 JST 2020
     */
    int updateByPrimaryKey(Organizations record);
}